[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = [
  "python3 -m ensurepip",
  "python3 -m pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[start]
cmd = "python main.py"
